export interface ProductCategoryItem {
  id: string;
  name: string;
  slug: string;
  description?: string;
  children?: ProductCategoryItem[];
}

export interface ProductItem {
  id: string;
  name: string;
  slug: string;
  description: string;
  categoryId: string;
  category?: { id?: string; name: string; slug?: string } | null;
  sku: string;
  referenceUrl?: string; // Internal admin supplier/procurement source link (hidden from storefront)
  price: number; // Ghana Cedis (GHS / GH₵)
  priceCny?: number; // Chinese Yuan / RMB (CNY / ¥)
  currency: string;
  unit: string;
  stockQuantity: number;
  stockStatus: 'IN_STOCK' | 'LOW_STOCK' | 'OUT_OF_STOCK' | string;
  originCountry: string;
  moq: number;
  status: 'DRAFT' | 'PUBLISHED' | string;
  featured: boolean;
  imageUrl?: string | null;
  galleryUrls: string[];
  createdAt: string;
  updatedAt: string;
}

export const INITIAL_CATEGORIES_STORE: ProductCategoryItem[] = [
  { id: 'cat-1', name: 'Tiles & Marble Slabs', slug: 'tiles-marble' },
  { id: 'cat-2', name: 'Tools & Construction Equipment', slug: 'tools-equipment' },
  { id: 'cat-3', name: 'Building Materials & Hardware', slug: 'building-materials' },
  { id: 'cat-4', name: 'Solar & Electrical Systems', slug: 'solar-electrical' },
  { id: 'cat-5', name: 'Sanitary Ware & Plumbing', slug: 'sanitary-ware' },
];

export const INITIAL_PRODUCTS_STORE: ProductItem[] = [
  {
    id: 'prod-1',
    name: 'Italian Carrara Porcelain Floor Tiles (60x120cm)',
    slug: 'italian-60x120-porcelain-floor-tiles',
    description: 'Premium nano-polished porcelain floor tiles with authentic Carrara marble pattern. High wear resistance, zero water absorption, and non-slip surface treatment.',
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Tiles & Marble Slabs', slug: 'tiles-marble' },
    sku: 'TILE-ITA-60120-CAR',
    price: 145.00,
    priceCny: 68.00,
    currency: 'GHS',
    unit: 'per box (1.44 sqm)',
    stockQuantity: 450,
    stockStatus: 'IN_STOCK',
    originCountry: 'Italy',
    moq: 20,
    status: 'PUBLISHED',
    featured: true,
    imageUrl: '/product_tiles.png',
    galleryUrls: ['/product_tiles.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Industrial 20V Brushless Cordless Drill & Impact Driver Set',
    slug: 'industrial-20v-brushless-cordless-drill-kit',
    description: 'Heavy duty construction grade cordless power tool combo kit. Includes 2x 4.0Ah Lithium-ion batteries, 1hr rapid charger, and rugged carrying case.',
    categoryId: 'cat-2',
    category: { id: 'cat-2', name: 'Tools & Construction Equipment', slug: 'tools-equipment' },
    sku: 'TOOL-20V-DRILL-KIT',
    price: 1850.00,
    priceCny: 880.00,
    currency: 'GHS',
    unit: 'per set',
    stockQuantity: 35,
    stockStatus: 'IN_STOCK',
    originCountry: 'Germany',
    moq: 1,
    status: 'PUBLISHED',
    featured: true,
    imageUrl: '/product_drill.png',
    galleryUrls: ['/product_drill.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Smart Biometric Fingerprint & Keypad Front Door Lock',
    slug: 'smart-biometric-fingerprint-front-door-lock',
    description: 'High-security 5-in-1 smart lock. Unlocks via Fingerprint, Mobile App, Passcode, RFID Card, and Emergency Mechanical Key with tamper alarm.',
    categoryId: 'cat-3',
    category: { id: 'cat-3', name: 'Building Materials & Hardware', slug: 'building-materials' },
    sku: 'SEC-SMART-LOCK-01',
    price: 1200.00,
    priceCny: 560.00,
    currency: 'GHS',
    unit: 'per piece',
    stockQuantity: 15,
    stockStatus: 'IN_STOCK',
    originCountry: 'China',
    moq: 5,
    status: 'PUBLISHED',
    featured: true,
    imageUrl: '/product_lock.png',
    galleryUrls: ['/product_lock.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Spanish Calacatta Gold Glossy Porcelain Wall Tiles (30x90cm)',
    slug: 'spanish-calacatta-gold-porcelain-wall-tiles',
    description: 'Luxury Spanish manufactured high-gloss ceramic & porcelain wall tiles with delicate gold veining. Ideal for master bathrooms and feature walls.',
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Tiles & Marble Slabs', slug: 'tiles-marble' },
    sku: 'TILE-ESP-3090-CAL-GOLD',
    price: 165.00,
    priceCny: 78.00,
    currency: 'GHS',
    unit: 'per box (1.35 sqm)',
    stockQuantity: 320,
    stockStatus: 'IN_STOCK',
    originCountry: 'Spain',
    moq: 15,
    status: 'PUBLISHED',
    featured: true,
    imageUrl: '/product_tiles.png',
    galleryUrls: ['/product_tiles.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: '5.5kVA Hybrid Solar Inverter & 10kWh Lithium Battery Storage System',
    slug: '5-5kva-hybrid-solar-inverter-lithium-battery-system',
    description: 'Complete off-grid and grid-tied intelligent solar power backup solution with dual MPPT charge controller and WiFi remote app monitoring.',
    categoryId: 'cat-4',
    category: { id: 'cat-4', name: 'Solar & Electrical Systems', slug: 'solar-electrical' },
    sku: 'SOLAR-HYBRID-55KVA-KIT',
    price: 28500.00,
    priceCny: 13500.00,
    currency: 'GHS',
    unit: 'per complete system',
    stockQuantity: 12,
    stockStatus: 'IN_STOCK',
    originCountry: 'China',
    moq: 1,
    status: 'PUBLISHED',
    featured: false,
    imageUrl: '/product_drill.png',
    galleryUrls: ['/product_drill.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    name: 'Luxury Brushed Gold Thermostatic Rain Shower System & Faucet',
    slug: 'luxury-brushed-gold-thermostatic-rain-shower-set',
    description: 'Premium solid brass wall-mounted thermostatic rainfall shower kit with PVD brushed gold finish, anti-scald cartridge, and handheld bidet spray.',
    categoryId: 'cat-5',
    category: { id: 'cat-5', name: 'Sanitary Ware & Plumbing', slug: 'sanitary-ware' },
    sku: 'BATH-GOLD-SHOWER-SET',
    price: 2450.00,
    priceCny: 1150.00,
    currency: 'GHS',
    unit: 'per set',
    stockQuantity: 28,
    stockStatus: 'IN_STOCK',
    originCountry: 'Italy',
    moq: 2,
    status: 'PUBLISHED',
    featured: false,
    imageUrl: '/product_lock.png',
    galleryUrls: ['/product_lock.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    name: 'Commercial Heavy-Duty Automatic Hydraulic Swing Gate Opener',
    slug: 'commercial-automatic-hydraulic-swing-gate-opener',
    description: 'Industrial grade automated dual swing gate actuator kit for heavy iron gates up to 800kg per leaf. Includes 4 remote transmitters and battery backup.',
    categoryId: 'cat-2',
    category: { id: 'cat-2', name: 'Tools & Construction Equipment', slug: 'tools-equipment' },
    sku: 'GATE-AUTO-HYD-500',
    price: 4800.00,
    priceCny: 2280.00,
    currency: 'GHS',
    unit: 'per set',
    stockQuantity: 18,
    stockStatus: 'IN_STOCK',
    originCountry: 'Italy',
    moq: 1,
    status: 'PUBLISHED',
    featured: false,
    imageUrl: '/product_drill.png',
    galleryUrls: ['/product_drill.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    name: 'Turkish Engineered Natural Oak Hardwood Flooring (15x190mm)',
    slug: 'turkish-engineered-natural-oak-hardwood-flooring',
    description: 'Authentic European oak hardwood plank flooring with multi-ply birch plywood core and click-lock profile. UV lacquer finish with 25-year structural warranty.',
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Tiles & Marble Slabs', slug: 'tiles-marble' },
    sku: 'WOOD-TURK-OAK-15190',
    price: 280.00,
    priceCny: 132.00,
    currency: 'GHS',
    unit: 'per sqm',
    stockQuantity: 600,
    stockStatus: 'IN_STOCK',
    originCountry: 'Turkey',
    moq: 25,
    status: 'PUBLISHED',
    featured: false,
    imageUrl: '/product_tiles.png',
    galleryUrls: ['/product_tiles.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-9',
    name: 'Ultra-HD Outdoor 4K Solar Powered AI Security Camera System',
    slug: 'ultra-hd-outdoor-4k-solar-ai-security-camera-kit',
    description: 'Wireless 100% wire-free 4K Ultra HD smart security camera set with integrated monocrystalline solar panel, human motion AI detection, and color night vision.',
    categoryId: 'cat-2',
    category: { id: 'cat-2', name: 'Tools & Construction Equipment', slug: 'tools-equipment' },
    sku: 'SEC-4K-SOLAR-CAM-KIT',
    price: 1650.00,
    priceCny: 780.00,
    currency: 'GHS',
    unit: 'per kit (4 cameras)',
    stockQuantity: 40,
    stockStatus: 'IN_STOCK',
    originCountry: 'China',
    moq: 1,
    status: 'PUBLISHED',
    featured: false,
    imageUrl: '/product_lock.png',
    galleryUrls: ['/product_lock.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-10',
    name: 'Industrial Portable Electric Concrete Mixer (350L Capacity)',
    slug: 'industrial-portable-electric-concrete-mixer-350l',
    description: 'Heavy duty site concrete and mortar batch mixer powered by a 3.0HP copper wire induction electric motor with puncture-proof transport wheels.',
    categoryId: 'cat-2',
    category: { id: 'cat-2', name: 'Tools & Construction Equipment', slug: 'tools-equipment' },
    sku: 'EQP-MIXER-350L-ELE',
    price: 6200.00,
    priceCny: 2950.00,
    currency: 'GHS',
    unit: 'per unit',
    stockQuantity: 10,
    stockStatus: 'IN_STOCK',
    originCountry: 'China',
    moq: 1,
    status: 'PUBLISHED',
    featured: false,
    imageUrl: '/product_drill.png',
    galleryUrls: ['/product_drill.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
