export interface PropertyItem {
  id: string;
  title: string;
  slug: string;
  description: string;
  listingType: "SALE" | "RENT" | string;
  propertyType: "HOUSE" | "LAND" | "APARTMENT" | "OFFICE_SPACE" | "WAREHOUSE" | string;
  status: "DRAFT" | "PUBLISHED" | string;
  price: number;
  currency: string;
  pricePeriod?: string;
  negotiable?: boolean;
  commission?: string;
  bedrooms: number;
  bathrooms: number;
  guestRooms?: number;
  boysQuarters?: number;
  garage?: number;
  sizeSqft?: number | null;
  livingAreaSqft?: number | null;
  locationAddress: string;
  city: string;
  region: string;
  country: string;
  featured: boolean;
  isFavourite?: boolean;
  imageUrl?: string | null;
  galleryUrls: string[];
  contactName?: string;
  contactPhone?: string;
  contactEmail?: string;
  ownerName?: string;
  ownerPhone?: string;
  ownerCompany?: string;
  agent?: { id: string; name: string } | null;
  amenities?: string[];
  createdAt: string;
  updatedAt: string;
}

export function sanitizePropertyForPublic(property: PropertyItem): PropertyItem {
  const { ownerName, ownerPhone, ownerCompany, ...publicData } = property;
  return {
    ...publicData,
    contactName: "Desmond Senanu",
    contactPhone: "+233 24 643 2493",
    contactEmail: "sales@loveridgeproperties.com",
  };
}

export const INITIAL_PROPERTIES_STORE: PropertyItem[] = [
  {
    "id": "prop-1788673496508",
    "title": "Luxury 6-Bedroom House for Sale – Peduase Lodge, Aburi",
    "slug": "luxury-6-bedroom-house-for-sale-peduase-lodge-aburi-5823",
    "description": "Luxury 6-Bedroom House for Sale – Peduase Lodge, Aburi\n\nLocated near former President Kufuor’s residence.\n\n* All bedrooms ensuite\n* Nanny’s quarters with kitchen\n* Massive private cinema room\n* Serene and prestigious estate\n\nPrice: US$1,000,000\nCall/WhatsApp: +233 24 643 2493",
    "listingType": "SALE",
    "propertyType": "HOUSE",
    "status": "PUBLISHED",
    "price": 1000000,
    "currency": "USD",
    "pricePeriod": "Hot Cake",
    "negotiable": true,
    "commission": "",
    "bedrooms": 6,
    "bathrooms": 6,
    "guestRooms": 1,
    "boysQuarters": 1,
    "garage": 2,
    "sizeSqft": 100,
    "livingAreaSqft": 100,
    "locationAddress": "Peduase Lodge, Aburi",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/uploads/prop-prop-1788673496508-cover-1788804484345-k4g4.webp",
    "galleryUrls": [
      "/uploads/prop-prop-1788673496508-gallery-0-1788804484346-jfx7.webp",
      "/uploads/prop-prop-1788673496508-gallery-1-1788804484348-rsq0.webp",
      "/uploads/prop-prop-1788673496508-gallery-2-1788804484349-h5mr.webp",
      "/uploads/prop-prop-1788673496508-gallery-3-1788804484350-1b5z.webp",
      "/uploads/prop-prop-1788673496508-gallery-4-1788804484351-cw3j.webp",
      "/uploads/prop-prop-1788673496508-gallery-5-1788804484352-axgp.webp",
      "/uploads/prop-prop-1788673496508-gallery-6-1788804484354-alzv.webp",
      "/uploads/prop-prop-1788673496508-gallery-7-1788804484355-bnte.webp",
      "/uploads/prop-prop-1788673496508-gallery-8-1788804484356-ikxn.webp"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "sales@loveridgeproperties.com",
    "amenities": [
      "Air conditioning",
      "Swimming Pool",
      "Cinema Room",
      "Gated Community Security",
      "Backup Generator",
      "Boys Quarters"
    ],
    "createdAt": "2026-09-06T05:44:58.251Z",
    "updatedAt": "2026-09-07T18:08:04.358Z"
  },
  {
    "id": "prop-1788676291872",
    "title": "Beautiful 4-Bedroom House for Sale",
    "slug": "beautiful-4-bedroom-house-for-sale-8573",
    "description": "Beautiful 4-Bedroom House for Sale\n\nLocation: Adjiringanor, East Legon\nBedrooms: 4\nPrice: US$280,000\n\nA beautiful and spacious home located in one of Accra’s most desirable residential areas.\n\nContact us today to schedule a viewing.",
    "listingType": "SALE",
    "propertyType": "HOUSE",
    "status": "PUBLISHED",
    "price": 280000,
    "currency": "USD",
    "pricePeriod": "outright purchase",
    "negotiable": true,
    "commission": "",
    "bedrooms": 4,
    "bathrooms": 4,
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "sizeSqft": 100,
    "livingAreaSqft": 100,
    "locationAddress": "East Legon Adjiringanor",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/uploads/prop-prop-1788676291872-cover-1788804485242-9jt8.webp",
    "galleryUrls": [
      "/uploads/prop-prop-1788676291872-gallery-0-1788804485243-ev7c.webp",
      "/uploads/prop-prop-1788676291872-gallery-1-1788804485244-pvmq.webp",
      "/uploads/prop-prop-1788676291872-gallery-2-1788804485244-f8zq.webp",
      "/uploads/prop-prop-1788676291872-gallery-3-1788804485245-aeyh.webp",
      "/uploads/prop-prop-1788676291872-gallery-4-1788804485247-dgwx.webp",
      "/uploads/prop-prop-1788676291872-gallery-5-1788804485248-uvjw.webp",
      "/uploads/prop-prop-1788676291872-gallery-6-1788804485251-a1xq.webp",
      "/uploads/prop-prop-1788676291872-gallery-7-1788804485254-lsu6.webp",
      "/uploads/prop-prop-1788676291872-gallery-8-1788804485255-0myp.webp",
      "/uploads/prop-prop-1788676291872-gallery-9-1788804485257-lgzq.webp",
      "/uploads/prop-prop-1788676291872-gallery-10-1788804485259-8cmb.webp",
      "/uploads/prop-prop-1788676291872-gallery-11-1788804485260-6pj3.webp",
      "/uploads/prop-prop-1788676291872-gallery-12-1788804485264-glpb.webp"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "sales@loveridgeproperties.com",
    "amenities": [
      "Air conditioning",
      "Modern Kitchen",
      "Paved Compound",
      "Water Reservoir",
      "Gated Security"
    ],
    "createdAt": "2026-09-06T06:31:34.296Z",
    "updatedAt": "2026-09-07T18:08:05.269Z"
  },
  {
    "id": "5d7876fb-e79c-45eb-806c-722c65778866",
    "title": "4-Bedroom House for Sale – Tse Addo, Burma Hills",
    "slug": "4-bedroom-house-for-sale-tse-addo-burma-hills-2819",
    "description": "Discover comfortable and secure living in Tse Addo – Burma Hills, one of Accra’s sought-after residential areas.\n\nProperty Features\n4 spacious bedrooms, all ensuite\nFitted kitchen\nBoys’ quarters\nSecure gated community\nSpacious and well-planned living areas\nSerene residential environment\n\nIdeal for: Family living, investment, or a premium residential home.\n\nCall/WhatsApp: +233 24 643 2493\nLoveridge Properties & Consult",
    "listingType": "SALE",
    "propertyType": "HOUSE",
    "status": "PUBLISHED",
    "price": 3800,
    "currency": "USD",
    "pricePeriod": "outright purchase",
    "negotiable": false,
    "commission": "",
    "bedrooms": 0,
    "bathrooms": 0,
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "sizeSqft": 100,
    "livingAreaSqft": null,
    "locationAddress": "Tse Addo – Burma Hills",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/uploads/prop-5d7876fb-e79c-45eb-806c-722c65778866.jpg",
    "galleryUrls": [
      "/uploads/prop-gallery-5d7876fb-e79c-45eb-806c-722c65778866-0.jpg",
      "/uploads/prop-gallery-5d7876fb-e79c-45eb-806c-722c65778866-1.jpg",
      "/uploads/prop-gallery-5d7876fb-e79c-45eb-806c-722c65778866-2.jpg",
      "/uploads/prop-gallery-5d7876fb-e79c-45eb-806c-722c65778866-3.jpg",
      "/uploads/prop-gallery-5d7876fb-e79c-45eb-806c-722c65778866-4.jpg"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ],
    "createdAt": "2026-08-15T12:55:44.643Z",
    "updatedAt": "2026-08-18T06:05:51.499Z"
  },
  {
    "id": "ca997015-a464-4bfe-97e6-824662d000c0",
    "title": "Office for rent at stanbic Heights ",
    "slug": "office-for-rent-at-stanbic-heights-8948",
    "description": "office for rent at Airport ",
    "listingType": "RENT",
    "propertyType": "OFFICE_SPACE",
    "status": "PUBLISHED",
    "price": 4500,
    "currency": "USD",
    "pricePeriod": "per month",
    "negotiable": false,
    "commission": "",
    "bedrooms": 0,
    "bathrooms": 0,
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "sizeSqft": 100,
    "livingAreaSqft": null,
    "locationAddress": "Airport",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/uploads/prop-ca997015-a464-4bfe-97e6-824662d000c0.jpg",
    "galleryUrls": [
      "/uploads/prop-gallery-ca997015-a464-4bfe-97e6-824662d000c0-0.jpg",
      "/uploads/prop-gallery-ca997015-a464-4bfe-97e6-824662d000c0-1.jpg",
      "/uploads/prop-gallery-ca997015-a464-4bfe-97e6-824662d000c0-2.jpg",
      "/uploads/prop-gallery-ca997015-a464-4bfe-97e6-824662d000c0-3.jpg"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ],
    "createdAt": "2026-08-10T21:27:38.972Z",
    "updatedAt": "2026-08-14T20:42:13.556Z"
  },
  {
    "id": "04957fa6-97d7-4919-a944-0feef02b2199",
    "title": "4,000 sqm Industrial Warehouse Facility for Sale - Spintex",
    "slug": "industrial-manufacturing-warehouse-spintex-road",
    "description": "Substantial 4,000 sqm industrial manufacturing and logistics complex on 3 acres of land along Spintex Road. Includes cold storage room facilities, heavy overhead crane rails, 500kVA transformer substation, and expansive turning yard for 40ft articulation trucks.",
    "listingType": "SALE",
    "propertyType": "WAREHOUSE",
    "status": "PUBLISHED",
    "price": 3500000,
    "currency": "USD",
    "pricePeriod": "outright purchase",
    "bedrooms": 0,
    "bathrooms": 8,
    "sizeSqft": 43055,
    "locationAddress": "Spintex Road Commercial Corridor",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/property_warehouse.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "createdAt": "2026-08-09T00:59:01.984Z",
    "updatedAt": "2026-08-09T00:59:01.984Z",
    "negotiable": false,
    "commission": "",
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "livingAreaSqft": null,
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ]
  },
  {
    "id": "f7645aaf-ca8a-4deb-bb3e-e59d6eb6b0ba",
    "title": "2,500 sqm Logistics Warehouse for Rent (Tema)",
    "slug": "high-bay-logistics-distribution-warehouse-tema",
    "description": "Modern 2,500 sqm high-bay logistics warehouse facility featuring 12m clear height clearance, 4 raised dock levelers, automated drive-in container doors, 24/7 security patrol, fire sprinkler systems, and dedicated administrative offices.",
    "listingType": "RENT",
    "propertyType": "WAREHOUSE",
    "status": "PUBLISHED",
    "price": 15000,
    "currency": "USD",
    "pricePeriod": "per month",
    "bedrooms": 0,
    "bathrooms": 4,
    "sizeSqft": 26910,
    "locationAddress": "Harbour Commercial Expressway",
    "city": "Tema",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/property_warehouse.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "createdAt": "2026-08-09T00:59:00.038Z",
    "updatedAt": "2026-08-09T00:59:00.038Z",
    "negotiable": false,
    "commission": "",
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "livingAreaSqft": null,
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ]
  },
  {
    "id": "c7011c4c-054a-4119-b7a7-95e7b3c6fbfd",
    "title": "Corporate Office Floor (850 sqm) for Sale - Airport City",
    "slug": "corporate-office-floor-airport-city-accra",
    "description": "Exclusive 850 sqm commercial office floor in an iconic Airport City high-rise. Fully partitioned into executive corner offices, boardrooms, open workstations, and cafeteria. High investment yield with blue-chip corporate tenant potential.",
    "listingType": "SALE",
    "propertyType": "OFFICE_SPACE",
    "status": "PUBLISHED",
    "price": 2600000,
    "currency": "USD",
    "pricePeriod": "outright purchase",
    "bedrooms": 0,
    "bathrooms": 6,
    "sizeSqft": 9149,
    "locationAddress": "Liberia Road, Airport City",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/property_office.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "createdAt": "2026-08-09T00:58:58.256Z",
    "updatedAt": "2026-08-09T00:58:58.256Z",
    "negotiable": false,
    "commission": "",
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "livingAreaSqft": null,
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ]
  },
  {
    "id": "bfd3891b-d7da-453b-9c30-b5dafe360efd",
    "title": "Grade-A Executive Office Suite (350 sqm) - Ridge",
    "slug": "grade-a-executive-office-suite-ridge-financial-district",
    "description": "Ultra-modern 350 sqm open-plan commercial office space located in Accra’s premier financial hub in Ridge. Features panoramic skyline views, high-speed fiber internet infrastructure, 24/7 power backup, central AC, and 10 dedicated underground parking slots.",
    "listingType": "RENT",
    "propertyType": "OFFICE_SPACE",
    "status": "PUBLISHED",
    "price": 8750,
    "currency": "USD",
    "pricePeriod": "per month",
    "bedrooms": 0,
    "bathrooms": 4,
    "sizeSqft": 3767,
    "locationAddress": "Financial District, Ridge",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/property_office.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "createdAt": "2026-08-09T00:58:56.542Z",
    "updatedAt": "2026-08-09T00:58:56.542Z",
    "negotiable": false,
    "commission": "",
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "livingAreaSqft": null,
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ]
  },
  {
    "id": "34cda0ae-a00b-4648-a751-1c1a2d41b340",
    "title": "2-Acre Industrial Land for Rent / Lease (Tema Port Zone)",
    "slug": "2-acre-industrial-lease-land-tema-heavy-industrial-zone",
    "description": "Prime fenced 2-acre industrial land plot available for long-term lease. Situated 5 minutes from Tema Port with high-capacity three-phase electrical power, piped water, and heavy vehicle paved access roads.",
    "listingType": "RENT",
    "propertyType": "LAND",
    "status": "PUBLISHED",
    "price": 4500,
    "currency": "USD",
    "pricePeriod": "per month",
    "bedrooms": 0,
    "bathrooms": 0,
    "sizeSqft": 87120,
    "locationAddress": "Heavy Industrial Area Zone 2",
    "city": "Tema",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/property_land.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "createdAt": "2026-08-09T00:58:54.474Z",
    "updatedAt": "2026-08-09T00:58:54.474Z",
    "negotiable": false,
    "commission": "",
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "livingAreaSqft": null,
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ]
  },
  {
    "id": "3323d27b-d1fe-4f92-a043-397719bbc587",
    "title": "Prime Commercial Land (1.2 Acres) - Cantonments",
    "slug": "prime-commercial-land-cantonments-embassy-quarter",
    "description": "Rare development opportunity! 1.2 acres of prime commercial/residential land located in the diplomatic zone of Cantonments. Fully registered title with Lands Commission clearance. Ideal for embassy headquarters, high-rise luxury apartments, or corporate office complex.",
    "listingType": "SALE",
    "propertyType": "LAND",
    "status": "PUBLISHED",
    "price": 1800000,
    "currency": "USD",
    "pricePeriod": "outright purchase",
    "bedrooms": 0,
    "bathrooms": 0,
    "sizeSqft": 52272,
    "locationAddress": "Cantonments Embassy Quarter",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/property_land.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "createdAt": "2026-08-06T17:40:52.657Z",
    "updatedAt": "2026-08-06T17:40:52.657Z",
    "negotiable": false,
    "commission": "",
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "livingAreaSqft": null,
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ]
  },
  {
    "id": "6b53e4ec-163a-4c2d-afb4-6f7848c87e05",
    "title": "Executive 2-Bedroom Serviced Apartment (Airport Residential)",
    "slug": "executive-2-bedroom-serviced-apartment-airport-residential",
    "description": "Modern high-rise residential apartment unit offering panoramic views of Airport Residential Area. Comes fully furnished with designer Italian furniture, gym access, standby generator, underground parking, and concierge service.",
    "listingType": "RENT",
    "propertyType": "APARTMENT",
    "status": "PUBLISHED",
    "price": 3200,
    "currency": "USD",
    "pricePeriod": "per month",
    "bedrooms": 2,
    "bathrooms": 2,
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "sizeSqft": 1800,
    "livingAreaSqft": null,
    "locationAddress": "Airport Residential Area",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": false,
    "imageUrl": "/property_villa.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "createdAt": "2026-08-06T17:40:51.218Z",
    "updatedAt": "2026-08-11T16:06:27.557Z",
    "negotiable": false,
    "commission": "",
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ]
  },
  {
    "id": "16621173-6b63-4793-a427-3bc4ff9b61fa",
    "title": "Luxury 4-Bedroom Smart Villa (East Legon)",
    "slug": "luxury-4-bedroom-smart-villa-east-legon",
    "description": "Ultra-modern 4-bedroom detached smart villa situated in the heart of East Legon. Features automated home systems, private infinity swimming pool, rooftop terrace, fully fitted Italian kitchen with Bosch appliances, solar backup system, and 24/7 security post.",
    "listingType": "SALE",
    "propertyType": "HOUSE",
    "status": "PUBLISHED",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ],
    "price": 450000,
    "currency": "USD",
    "pricePeriod": "outright purchase",
    "negotiable": false,
    "bedrooms": 4,
    "bathrooms": 5,
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "sizeSqft": 4500,
    "livingAreaSqft": null,
    "locationAddress": "Boundary Road, East Legon",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/property_villa.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "createdAt": "2026-08-06T17:40:49.453Z",
    "updatedAt": "2026-08-06T17:40:49.453Z",
    "commission": "",
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": ""
  },
  {
    "id": "d856d6a4-45e5-49d4-8348-358af989bfb0",
    "title": "0.8 Acre Prime Commercial Land",
    "slug": "prime-commercial-development-land-cantonments",
    "description": "Rare development opportunity in high-demand Cantonments district. Land is titled with clear legal ownership, ideal for luxury apartments, boutique office complex, or diplomatic residency building.",
    "listingType": "SALE",
    "propertyType": "LAND",
    "status": "PUBLISHED",
    "price": 1800000,
    "currency": "USD",
    "pricePeriod": "outright purchase",
    "negotiable": false,
    "commission": "",
    "bedrooms": 0,
    "bathrooms": 0,
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "sizeSqft": 34848,
    "livingAreaSqft": null,
    "locationAddress": "Rangoon Lane, Cantonments",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/property_villa.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ],
    "createdAt": "2026-08-06T17:37:09.930Z",
    "updatedAt": "2026-08-06T17:37:09.930Z"
  },
  {
    "id": "f51639a6-8621-467f-94c9-901fd474c81d",
    "title": "Executive 2-Bedroom Furnished Apartment",
    "slug": "executive-2-bed-apartment-airport-residential",
    "description": "Modern high-rise residential apartment unit offering panoramic views of Airport Residential Area. Comes fully furnished with designer Italian furniture, gym access, standby generator, underground parking, and concierge service.",
    "listingType": "RENT",
    "propertyType": "APARTMENT",
    "status": "PUBLISHED",
    "price": 3200,
    "currency": "USD",
    "pricePeriod": "per month",
    "negotiable": false,
    "commission": "",
    "bedrooms": 2,
    "bathrooms": 2,
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "sizeSqft": 1800,
    "livingAreaSqft": null,
    "locationAddress": "Airport Bypass Road",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/property_villa.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ],
    "createdAt": "2026-08-06T17:37:08.444Z",
    "updatedAt": "2026-08-06T17:37:08.444Z"
  },
  {
    "id": "f277bc5a-add0-49bd-b14c-17829ac95dc7",
    "title": "Luxury 4-Bedroom Gated Villa with Private Pool",
    "slug": "luxury-4-bedroom-villa-east-legon",
    "description": "An architectural masterpiece located in the heart of East Legon. Features 4 ensuite bedrooms, a private infinity pool, fully equipped modern kitchen, high-ceiling living space, smart automation, solar backup power, and 24/7 security guard post.",
    "listingType": "SALE",
    "propertyType": "HOUSE",
    "status": "PUBLISHED",
    "price": 650000,
    "currency": "USD",
    "pricePeriod": "outright purchase",
    "negotiable": false,
    "commission": "",
    "bedrooms": 4,
    "bathrooms": 5,
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "sizeSqft": 4500,
    "livingAreaSqft": null,
    "locationAddress": "Lagos Avenue, East Legon",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/property_villa.png",
    "galleryUrls": [
      "/property_villa.png"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "ownerName": "",
    "ownerPhone": "",
    "ownerCompany": "",
    "amenities": [
      "Air conditioning",
      "Fitted Kitchen",
      "Ample Parking Space",
      "24/7 Security & CCTV",
      "Backup Generator"
    ],
    "createdAt": "2026-08-06T17:37:06.811Z",
    "updatedAt": "2026-08-06T17:37:06.811Z"
  },
  {
    "id": "prop-1788299849124",
    "title": "House for sale ",
    "slug": "house-for-sale--1189",
    "description": "Property listing draft saved automatically.",
    "listingType": "SALE",
    "propertyType": "HOUSE",
    "status": "PUBLISHED",
    "price": 450000,
    "currency": "USD",
    "pricePeriod": "Hot cake ",
    "negotiable": true,
    "commission": "",
    "bedrooms": 4,
    "bathrooms": 4,
    "guestRooms": 0,
    "boysQuarters": 0,
    "garage": 0,
    "sizeSqft": 100,
    "livingAreaSqft": 100,
    "locationAddress": "East Legon",
    "city": "Accra",
    "region": "Greater Accra",
    "country": "Ghana",
    "featured": true,
    "imageUrl": "/uploads/prop-prop-1788299849124.jpg",
    "galleryUrls": [
      "/uploads/prop-gallery-prop-1788299849124-0.jpg",
      "/uploads/prop-gallery-prop-1788299849124-1.jpg",
      "/uploads/prop-gallery-prop-1788299849124-2.jpg"
    ],
    "contactName": "Desmond Senanu",
    "contactPhone": "+233 24 643 2493",
    "contactEmail": "agent@loveridge.com",
    "ownerName": "Green",
    "ownerPhone": "0247859380",
    "ownerCompany": "Green Burg",
    "amenities": [
      "Air conditioning",
      "Cooker",
      "Washing machine",
      "Fans",
      "Satellite tv",
      "Internet access",
      "Garden",
      "Garage",
      "Annexe (Boys' quarters)",
      "Roof terrace"
    ],
    "createdAt": "2026-09-01T22:03:01.189Z",
    "updatedAt": "2026-09-01T22:03:01.189Z"
  }
];
